export const companies = [
  'Microsoft',
  'Google',
  'Amazon',
  'Facebook',
  'Apple',
  'Netflix',
  'Tesla',
  'IBM',
  'Intel',
  'Cisco',
  'Oracle',
  'Qualcomm',
];

export const designations = [
  'Software Engineer',
  'Senior Software Engineer',
  'Principal Software Engineer',
  'Software Architect',
  'Project Manager',
  'Product Manager',
  'Data Scientist',
  'Machine Learning Engineer',
  'Data Analyst',
  'Business Analyst',
  'DevOps Engineer',
  'System Administrator',
  'Network Engineer',
  'Database Administrator',
  'UX Designer',
  'UI Designer',
  'Graphic Designer',
  'Web Developer',
  'Frontend Developer',
  'Backend Developer',
];
